### ISSUE TITLE
sub.ready() is true too early

### ISSUE THREAD

**Issue by Twisterking** [englue/meteor-publish-composite#100]
Hi guys!
So I have a Meteor app with a React frontend using MDGs standard `react-meteor-data` package.
In some of my packages I subscribe to **two publishComposite publications** in one Meteor datacontainer:
```
const ItemListContainer = createContainer((props) => {
    const sub1 = Meteor.subscribe('getItems', props.supplierId); // publishComposite
    const sub2 = Meteor.subscribe('getItems', props.otherSupplierId); // publishComposite
    let loading = !sub1.ready() || !sub2.ready();
    return {
        loading,
        otherStuff ...
    }
}
```

My problem is now that my `loading` var is not working properly, so my components are already rendering the first time when my subscriptions **are not ready yet**!
Any ideas on this?

**Comment by JWDobken** [comment]
I think this is the same issue https://github.com/englue/meteor-publish-composite/issues/67

**Comment by reywood** [comment]
Doesn't seem to be exactly the same as #67. I believe the problem is that you're just evaluating `.ready()` once immediately after subscribing. You need to evaluate `.ready()` reactively. You could try making `loading` into a function rather than a static var, something like `let loading = () => !sub1.ready() || !sub2.ready();`.
