### ISSUE TITLE
Trigger error callbacks on errors within nested functions

### ISSUE THREAD

**Issue by fongandrew** [englue/meteor-publish-composite#31]
It is possible to pass an `onError` callback to `Meteor.subscribe` that is fired when there is an error within the publication or the publication explicitly calls `this.error()`.

This doesn't appear to work if the error occurs within a nested `find` function (although explicitly calling `this.error()` does still work) -- that is ...

```javascript
Meteor.publishComposite('mySub', {
  find: function() {
    return Universes.find();
    throw new Meteor.Error(500, "error"); // Triggers onError callback
  },
  children: [
    { 
      find: function(doc) {
        throw new Meteor.Error(500, "error"); // Does not trigger onError callback
      }
    }, {
      find: function(doc) { 
        this.error(500); // Triggers onError callback
      }
    }
  ]
});
```

It'd be nice if publish-composite had an option to automatically wrap each child find function in a try/catch block and call this.error if any of them fail.

**Comment by reywood** [comment]
The `throw` in your first `find` function is unreachable due to the `return` preceding it. It will never be called. Not sure why you're seeing the onError callback getting triggered.

In any event, the current behavior is consistent with Meteor's `publish` method. Probably best to stick with what people will expect when possible.

**Comment by fongandrew** [comment]
Oh, huh, that's embarrassing. Totally didn't see the return.

**Comment by reywood** [comment]
Happens to the best of us :)
