### ISSUE TITLE
A question on performance

### ISSUE THREAD

**Issue by derwaldgeist** [englue/meteor-publish-composite#71]
I have a scenario that is quite similar to your example: a list of posts, and I want to publish all authors related to these posts.

If I understand this package correctly, it would perform a database query for every single user, since it iterates over the cursor of the posts.

I would expect a significant performance degradation if you use this in combination with endless scrolling, because the total number of parent documents (the posts in this case) would grow larger and larger.

Is this really the case, or does this package use some caching under the hood (or maybe even bundling of database queries) to prevent this?

**Comment by nate331** [comment]
I would like to hear more about that as well.

**Comment by andresberrios** [comment]
+1
I would also like to know how the queries are handled. If it iterates over the parentNodes making one query for each node (and so on, in deeper levels of the tree), then the amount of queries can be huge in many cases, which is really undesirable. Maybe a possible improvement would be to return a collection object and a Mongo criteria object in each `find` function and merging them together with `$or` to build one query for all the nodes in that level, and then use Minimongo on the server to run the individual queries in-memory to attach the documents to the right nodes, etc., instead of returning the cursors directly, unless there was a way to merge the cursors themselves somehow.
@reywood do you think this makes sense? Or is it doing something like this already?
Thanks for this, it looks really promising if the performance is good.

**Comment by derwaldgeist** [comment]
I added a log statement in the child document retrieval section, and indeed I got a log statement for every parent object. Since I saw this, I am only using publishComposite if I am sure that the amount of child objects is not too high. For the post and author scenario, it would lead to many unnecessary retrievals of users that have already been retrieved, so I am not using it in this scenario any more.

**Comment by sabativi** [comment]
I think, this should be highlighted somewhere in the README as limits of this package.

**Comment by solace** [comment]
Is there a technical reason why an `$in` or an `$or` of the parent objects can't be used to create a single query instead of multiple separate queries?

**Comment by malhal** [comment]
Because the $in objectids query could be massive.

**Comment by reywood** [comment]
As you said, a new cursor will be opened for every parent document when calling the child `find` function. I don't recommend using publishComposite for very large datasets (and probably not with infinite scrolling either).

Any solution to the mongodb "join" problem is going to have tradeoffs. This package aims for simplicity, flexibility, and ease of use, but performance suffers when publishing too many documents. From what I've seen, there are other packages that are probably better suited to publishing large datasets, but are less straightforward to use, though that's a matter of opinion.

To answer @solace's question, that is a possibility, but would require a rather large redesign of this package. Unfortunately, I don't have as much free time as I would like to explore a solution like that. I wholeheartedly encourage you to take up the challenge though. :)

**Comment by reywood** [comment]
I've added a section to the README about possible performance issues with large datasets.
