### ISSUE TITLE
Publication observers aren't getting removed

### ISSUE THREAD

**Issue by mikepaszkiewicz** [englue/meteor-publish-composite#86]
I've been noticing my memory creeping up every few days eventually to 100%, leading to a crash, on a server that I use occasionally for dev work. Checked Kadira, and my created observers are always higher than deleted ones for my most-subbed pubComposites.

This seems indicative of a memory leak, but I can't find any info about repairing a leak dealing with observers. Should I be looking at the pubComposite itself for the amount of data it's querying, how often I'm subscribing to it, etc? Any advice or direction would be super helpful, thanks!

**Comment by reywood** [comment]
The only ways I could see this happening is if the `onStop` event of the publication wasn't being called correctly or if there is a bug in Meteor itself, though there could be other causes I suppose. Have you seen any errors related to your publications in logs?

P.S. Sorry for the lateness of my reply. Haven't had a lot of time for this project. Since you may have moved on from using this package, I'm going to close this issue. I'll reopen if you're still interested in exploring a solution.

**Comment by mikepaszkiewicz** [comment]
No problem - still using the package, the problem ended up being completed unrelated. Thanks!
